### ISSUE TITLE
Define a SparkConn class

### ISSUE THREAD

**Issue by nlosilva1** [Ica-Riluci/simSpark#2]

**Comment by nlosilva1** [comment]
interface：
connection(hostname,portname)    //init function
accept() let the connection to accept a single message
getHost()/getPort() get the host or port
sendMessage(dict) give a dictionary of message ,including 'host','port',and a json string

**Comment by Ica-Riluci** [comment]
Definition a message:
A dictionary consists of:
1. `type`
  possible value: `check_worker_timeout`, `register_worker`, `register_application`, `executor_stage_changed`, `remove_application`, `kill_executor`, `driver_state_changed`, `worker_heartbeat`, `master_changed_acknowledge`, `worker_schedule_state_response`, `worker_latest_state`, `unregister_application`, `request_submit_driver`,  `request_kill_driver`, `request_driver_status`, `request_master_state`, `request_executors`, `kill_executors`
2. `value`

**Comment by Ica-Riluci** [comment]
`check_worker_timeout` message:
The `value` contains nothing
`reg_worker` message:
`value` is a dictionary which looks like:
{
`host` : the host IP of the worker
`port` : the port listened by the worker
`cores` : the cores the worker is allocated
`ram` : the sizes of RAM the worker is allocated in the unit MB
}

**Comment by Ica-Riluci** [comment]
`reg_app` message:
`value` is a dictionary which looks like:
{
`driver`: {`host` : the host IP of its **driver**
`port` : the port of its driver}
`app` : the attribute of the application, like `app_name`
}

`reg_app_ack` message:
`value` is the `app_id` of the application

**Comment by nlosilva1** [comment]
master从外部收到的消息：
    1、worker的注册消息（包含worker地址和端口）（包括reconnect？）
    2、application注册的消息
    3、driver申请资源（executor）的消息
    4、worker的heartbeat
    5、worker返回申请完毕的executor信息&executor状态变化

master发出去的信息
    1、向worker申请使用已修订数量executor
     2、向driver发送申请完毕的executor

**Comment by nlosilva1** [comment]
worker从外部收到的消息：
1、master发来的worker成功注册到master的信息
2、master申请一定数量的executor的消息
3、executor状态发生变化的消息

worker向外发出的消息：
1、删除对应的executor
2、向master发出的初始注册的信息（重新注册的信息）
3、向master发出的heartbeat
4、向master发出executor的状态变化

(masterchange)
（会向自己发送reregisterwithmaster、清理工作目录 信息）

**Comment by Ica-Riluci** [comment]
A initial version is done with #3
